// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seguros.Data;

#nullable disable

namespace Seguros.Data.Migrations
{
    [DbContext(typeof(SegurosDbContext))]
    [Migration("20260910164803_InicialEsquema")]
    partial class InicialEsquema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Seguros.Domain.Entities.Asegurado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domicilio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NroDocumento")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductorId", "TipoDocumento", "NroDocumento")
                        .IsUnique();

                    b.ToTable("Asegurados");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Compania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companias");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.CompaniaRamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompaniaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PorcentajeComision")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RamoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RamoId");

                    b.HasIndex("CompaniaId", "RamoId")
                        .IsUnique();

                    b.ToTable("CompaniaRamos");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Endoso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anulado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PolizaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolizaId");

                    b.ToTable("Endosos");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PeriodoDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodoHasta")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductorId");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.LiquidacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoComision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PolizaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId");

                    b.HasIndex("PolizaId");

                    b.ToTable("LiquidacionDetalles");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Poliza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AseguradoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cobertura")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompaniaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionRiesgo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsFlota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PolizaOrigenId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Premio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Producto")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VencimientoGestionado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("VigenciaHasta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AseguradoId");

                    b.HasIndex("PolizaOrigenId");

                    b.HasIndex("ProductorId");

                    b.HasIndex("RamoId");

                    b.HasIndex("CompaniaId", "Numero")
                        .IsUnique();

                    b.ToTable("Polizas");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Productor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Productores");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Ramo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ramos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Autos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Motos"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Vida"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vida Colectivo"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Vida Individual"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Vida Obligatorio"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Incendio"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Combinado Familiar"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Responsabilidad Civil"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Accidentes Personales"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Integral de Comercio"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Caución"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Transporte / Cascos"
                        });
                });

            modelBuilder.Entity("Seguros.Domain.Entities.UnidadFlota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PolizaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolizaId");

                    b.ToTable("UnidadesFlota");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Asegurado", b =>
                {
                    b.HasOne("Seguros.Domain.Entities.Productor", "Productor")
                        .WithMany("Asegurados")
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productor");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.CompaniaRamo", b =>
                {
                    b.HasOne("Seguros.Domain.Entities.Compania", "Compania")
                        .WithMany("RamosOperados")
                        .HasForeignKey("CompaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seguros.Domain.Entities.Ramo", "Ramo")
                        .WithMany()
                        .HasForeignKey("RamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compania");

                    b.Navigation("Ramo");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Endoso", b =>
                {
                    b.HasOne("Seguros.Domain.Entities.Poliza", "Poliza")
                        .WithMany("Endosos")
                        .HasForeignKey("PolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Liquidacion", b =>
                {
                    b.HasOne("Seguros.Domain.Entities.Productor", "Productor")
                        .WithMany()
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productor");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.LiquidacionDetalle", b =>
                {
                    b.HasOne("Seguros.Domain.Entities.Liquidacion", "Liquidacion")
                        .WithMany("Detalles")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seguros.Domain.Entities.Poliza", "Poliza")
                        .WithMany()
                        .HasForeignKey("PolizaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liquidacion");

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Poliza", b =>
                {
                    b.HasOne("Seguros.Domain.Entities.Asegurado", "Asegurado")
                        .WithMany("Polizas")
                        .HasForeignKey("AseguradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seguros.Domain.Entities.Compania", "Compania")
                        .WithMany("Polizas")
                        .HasForeignKey("CompaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seguros.Domain.Entities.Poliza", "PolizaOrigen")
                        .WithMany()
                        .HasForeignKey("PolizaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Seguros.Domain.Entities.Productor", "Productor")
                        .WithMany("Polizas")
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seguros.Domain.Entities.Ramo", "Ramo")
                        .WithMany()
                        .HasForeignKey("RamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asegurado");

                    b.Navigation("Compania");

                    b.Navigation("PolizaOrigen");

                    b.Navigation("Productor");

                    b.Navigation("Ramo");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.UnidadFlota", b =>
                {
                    b.HasOne("Seguros.Domain.Entities.Poliza", "Poliza")
                        .WithMany("Unidades")
                        .HasForeignKey("PolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Asegurado", b =>
                {
                    b.Navigation("Polizas");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Compania", b =>
                {
                    b.Navigation("Polizas");

                    b.Navigation("RamosOperados");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Liquidacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Poliza", b =>
                {
                    b.Navigation("Endosos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Seguros.Domain.Entities.Productor", b =>
                {
                    b.Navigation("Asegurados");

                    b.Navigation("Polizas");
                });
#pragma warning restore 612, 618
        }
    }
}
